//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    public partial class Budget
    {
        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlBudgetWarning control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBudgetWarning;

        /// <summary>
        /// lblBudgetWarning control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBudgetWarning;

        /// <summary>
        /// ddlMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// txtLimitAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLimitAmount;

        /// <summary>
        /// rfvLimit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLimit;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// lblCurrentMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentMonth;

        /// <summary>
        /// lblBudgetAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBudgetAmount;

        /// <summary>
        /// lblSpentAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSpentAmount;

        /// <summary>
        /// lblRemainingAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRemainingAmount;

        /// <summary>
        /// lblPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPercent;

        /// <summary>
        /// pnlProgress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlProgress;

        /// <summary>
        /// gvBudgets control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvBudgets;
    }
}
