//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    public partial class Default
    {
        /// <summary>
        /// pnlBudgetWarning control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBudgetWarning;

        /// <summary>
        /// lblBudgetWarning control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBudgetWarning;

        /// <summary>
        /// pnlBudgetInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBudgetInfo;

        /// <summary>
        /// lblBudgetInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBudgetInfo;

        /// <summary>
        /// lblTotalExpense control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalExpense;

        /// <summary>
        /// lblBudgetRemaining control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBudgetRemaining;

        /// <summary>
        /// lblCategoryCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCategoryCount;

        /// <summary>
        /// lblGoalCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblGoalCount;

        /// <summary>
        /// gvRecentExpenses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvRecentExpenses;

        /// <summary>
        /// lnkViewAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkViewAll;

        /// <summary>
        /// lnkAddExpense control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkAddExpense;

        /// <summary>
        /// lnkSetBudget control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkSetBudget;

        /// <summary>
        /// lnkViewReport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkViewReport;
    }
}
