//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    public partial class Expense
    {
        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblFormTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;

        /// <summary>
        /// txtAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAmount;

        /// <summary>
        /// rfvAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAmount;

        /// <summary>
        /// ddlCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>
        /// rfvCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCategory;

        /// <summary>
        /// txtExpenseDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtExpenseDate;

        /// <summary>
        /// rfvDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDate;

        /// <summary>
        /// txtNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNote;

        /// <summary>
        /// hfExpenseID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfExpenseID;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>
        /// ddlMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlFilterCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterCategory;

        /// <summary>
        /// lblTotalAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalAmount;

        /// <summary>
        /// gvExpenses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvExpenses;
    }
}
