//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    public partial class Goal
    {
        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblFormTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;

        /// <summary>
        /// txtGoalName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtGoalName;

        /// <summary>
        /// rfvGoalName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGoalName;

        /// <summary>
        /// txtTargetAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTargetAmount;

        /// <summary>
        /// rfvTarget control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTarget;

        /// <summary>
        /// txtCurrentAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrentAmount;

        /// <summary>
        /// txtDeadline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDeadline;

        /// <summary>
        /// hfGoalID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfGoalID;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>
        /// rptGoals control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptGoals;

        /// <summary>
        /// lblNoGoals control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoGoals;

        /// <summary>
        /// pnlAddMoney control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAddMoney;

        /// <summary>
        /// lblAddMoneyGoal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAddMoneyGoal;

        /// <summary>
        /// txtAddAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddAmount;

        /// <summary>
        /// hfAddMoneyGoalID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfAddMoneyGoalID;

        /// <summary>
        /// btnConfirmAdd control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmAdd;

        /// <summary>
        /// btnCancelAdd control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelAdd;
    }
}
