//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    public partial class Report
    {
        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlReportType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlReportType;

        /// <summary>
        /// lblTotalYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalYear;

        /// <summary>
        /// lblYear1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblYear1;

        /// <summary>
        /// lblAvgMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAvgMonth;

        /// <summary>
        /// lblTopCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTopCategory;

        /// <summary>
        /// lblChartTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblChartTitle;

        /// <summary>
        /// chartExpense control.
        /// </summary>
        protected global::System.Web.UI.DataVisualization.Charting.Chart chartExpense;

        /// <summary>
        /// pnlPieChart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPieChart;

        /// <summary>
        /// chartPie control.
        /// </summary>
        protected global::System.Web.UI.DataVisualization.Charting.Chart chartPie;

        /// <summary>
        /// gvReport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvReport;

        /// <summary>
        /// lblGrandTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblGrandTotal;
    }
}
