//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    public partial class SiteMaster
    {
        /// <summary>
        /// lnkDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;

        /// <summary>
        /// lnkExpense control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkExpense;

        /// <summary>
        /// lnkCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkCategory;

        /// <summary>
        /// lnkBudget control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBudget;

        /// <summary>
        /// lnkGoal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkGoal;

        /// <summary>
        /// lnkReport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkReport;

        /// <summary>
        /// lblUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsername;

        /// <summary>
        /// lnkLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkLogout;
    }
}
